
---
Name: Tsuru
ModulesDir: modules
IncludeDir: include
SourceDir: source
RpxDir: +/rpxs
Modules:
  - carterra             # Carterra worldmaps
  - cheats               # Cheat menu
  - collisionconditions  # Fixes collision conditions for some actors
  - csscripts            # Custom world map scripts
  - customactors         # Custom sprites/actors
  - debug                # Debugging features
# - experiments          # Experimental things
  - framebuffer          # Framebuffer-related fixes
  - initializer          # Initializer
  - layout               # Custom layouts
  - misc                 # Miscellaneous items
  - patchedactors        # Patches for existing actors
  - powerup              # Custom powerups
  - profile              # Extra profile and sprite slots
  - resloader            # Resource loader
  - sarcloader           # Allow loading uncompressed .sarc levels
  - savemgr              # Manages the custom savedata files
  - sead                 # Patches for the sead library
  - sound                # Patches that affect sound
  - titlescreen          # Title screen patches
  - yoshicolors          # Extra colors for Yoshi
Defines:
  - NO_INTELLISENSE_HACK
  - TSURU_DEBUG

Targets:
  US: ~
  EU: ~
  JP: ~
  Template/SME:
    Defines:
      - TARGET_SME
  SME_US:
    Extends: SME
    AddrMap: US
    BaseRpx: US
  SME_EU:
    Extends: SME
    AddrMap: EU
    BaseRpx: EU
  SME_JP:
    Extends: SME
    AddrMap: JP
    BaseRpx: JP
